name: Deploy ERD (Prisma) to Cloudflare Pages

on:
  push:

jobs:
  build-and-deploy-erd:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@v4
      - name: Generate ER Diagrams
        # You can specify a custom output directory with --output-dir option if needed
        run: npx @liam-hq/cli erd build --input schema.sql --format postgres
      - name: Deploy ERD to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./dist --project-name=lifti-db-erd
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}